export const rcadsStatements = [
  { text: 'I worry about things' },
  { text: 'I feel sad or empty' },
  { text: 'When I have a problem, I get a funny feeling in my stomach' },
  { text: 'I worry when I think I have done poorly at something' },
  { text: 'I would feel afraid of being on my own at home' },
  { text: 'Nothing is much fun anymore' },
  { text: 'I feel scared when I have to take a test' },
  { text: 'I feel worried when I think someone is angry with me' },
  { text: 'I worry about being away from my parents' },
  { text: 'I get bothered by bad or silly thoughts or pictures in my mind' },
  { text: 'I have trouble sleeping' },
  { text: 'I worry that I will do badly at my school work' },
  { text: 'I worry that something awful will happen to someone in my family' },
  { text: 'I suddenly feel as if I can\'t breathe when there is no reason for this' },
  { text: 'I have problems with my appetite' },
  { text: 'I have to keep checking that I have done things right (like the switch is off, or the door is locked)' },
  { text: 'I feel scared if I have to sleep on my own' },
  { text: 'I have trouble going to school in the mornings because I feel nervous or afraid' },
  { text: 'I have no energy for things' },
  { text: 'I worry I might look foolish' },
  { text: 'I feel nervous when I have to speak in front of a group' },
  { text: 'I worry about what others think of me' },
  { text: 'I feel anxious when I have to make a decision' },
  { text: 'I worry about making friends' },
  { text: 'I feel uneasy in new situations' },
  { text: 'I worry about being in a crowd' },
  { text: 'I feel self-conscious about my appearance' },
  { text: 'I worry about being teased or bullied' },
  { text: 'I feel anxious about trying new things' },
  { text: 'I worry about being in trouble' },
  { text: 'I feel scared when I hear a loud noise' },
  { text: 'I worry about being separated from my parents' },
  { text: 'I feel nervous when I have to meet new people' },
  { text: 'I worry about not being good enough' },
  { text: 'I feel anxious about going to the doctor or dentist' },
  { text: 'I worry about being in a situation where I might get hurt' },
  { text: 'I feel scared when I see or hear about something bad happening' },
  { text: 'I worry about not being able to do something' },
  { text: 'I feel nervous when I have to perform in front of others' },
  { text: 'I worry about being different from others' },
  { text: 'I feel anxious about being in a situation where I might be embarrassed' },
  { text: 'I worry about not being liked by others' },
  { text: 'I feel scared when I have to do something new' },
  { text: 'I worry about being in a situation where I might fail' },
]; 